"""
ged_factor_analysis.py

Sub-analyses of per-trial detection performance (F1, MAE) vs subject-level factors.

Saves:
 - per-factor plots (2x1: F1 / MAE) for IC and FC
 - CSVs with group statistics and test results

Usage:
  Put this file under:
    headwalk/gait_events_detection/testing/ged_factor_analysis.py

  Run:
    python ged_factor_analysis.py

Author: generated (adapted to your codebase)
Date: 2026-02-27
"""

from __future__ import annotations
import re
from pathlib import Path
from typing import Dict, Any, List, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from itertools import combinations

# -----------------------
# PATHS / CONFIG
# -----------------------
ROOT = Path(__file__).resolve().parents[2]  # headwalk
METADATA_XLSX = ROOT / "metadata" / "ICICLE Gait - 20250414_Paolo.xlsx"
PLOTS_OUTDIR = ROOT / "gait_events_detection" / "testing" / "results" / "_sub_analysis_plot"
PER_TRIAL_CSV = ROOT / "gait_events_detection" / "testing" / "results" / "_analysis_plots" / "per_trial_metrics.csv"  # generated by earlier script

PLOTS_OUTDIR.mkdir(parents=True, exist_ok=True)

# regex to extract subject code and timepoint from filename:
# example filename: 20140616-104931-INGC116F2_SC.h5 -> subject_code=INGC116, tp=F2
_SUBJECT_RE = re.compile(r"(ING[CP]\d{3})(?:[^\w]|_)?(F[234])", re.IGNORECASE)

# Map timepoint suffix (F2/F3/F4) to the excel columns you described.
# Adjust these column names if your Excel uses slightly different names.
TIMEPOINT_MAP = {
    # F2 -> t36 (you wrote Age_t36 etc.)
    "F2": {
        "age_col": "Age_t36",
        "hy_col": "HY_t36",
        "phen_col": "Motor_Phenotype_t36",
        "nfog_col": "NFOG_Binary_t32",  # user list had NFOG_t32
    },
    "F3": {
        "age_col": "Age_t54",
        "hy_col": "HY_t54",
        "phen_col": "Motor_Phenotype_t54",
        "nfog_col": "NFOG_Binary_t54",
    },
    "F4": {
        "age_col": "Age_t72",
        "hy_col": "HY_t72",
        "phen_col": "Motor_Phenotype_t72",
        "nfog_col": "NFOG_Binary_t72",
    },
}

# Age bins definition (labels)
AGE_BINS = [0, 40, 50, 60, 70, 80, 90, 200]  # 0-39 catch-all, >90 in last bin
AGE_LABELS = ["<40", "40-50", "51-60", "61-70", "71-80", "81-90", ">90"]

# colors for plotting (arbitrary pleasing palette)
GROUP_COLORS = {
    "C": "#1f77b4",  # blue
    "P": "#ff7f0e",  # orange
    # extra colors for groupings (age, sex, phenotype)
}

# -----------------------
# UTILITIES
# -----------------------
def extract_subject_and_tp(filename: str) -> Tuple[str | None, str | None]:
    """
    Extract subject code and timepoint from filename.
    Returns (subject_code, timepoint e.g. 'F2') or (None, None) on failure.
    """
    m = _SUBJECT_RE.search(filename)
    if not m:
        return None, None
    subj = m.group(1).upper()
    tp = m.group(2).upper()
    return subj, tp


def age_to_bin(age_val: float) -> str:
    """
    Place a numeric age into the AGE_LABELS categories.
    """
    try:
        a = float(age_val)
    except Exception:
        return "Unknown"
    idx = np.digitize([a], AGE_BINS, right=False)[0] - 1
    if idx < 0 or idx >= len(AGE_LABELS):
        return "Unknown"
    return AGE_LABELS[idx]


def safe_unique_list(vals) -> List:
    """Return unique list preserving order, excluding nan/None/empty."""
    seen = set()
    out = []
    for v in list(vals):
        if pd.isna(v):
            continue
        if v not in seen:
            seen.add(v)
            out.append(v)
    return out


def pairwise_mwu_with_bonferroni(groups: Dict[str, np.ndarray]) -> pd.DataFrame:
    """
    For dictionary group_name -> values array, compute pairwise Mann-Whitney U tests,
    apply Bonferroni correction for multiple comparisons (multiply p by n_comparisons).
    Returns DataFrame with columns: group1, group2, p_uncorrected, p_bonf, stat.
    """
    names = list(groups.keys())
    n = len(names)
    comparisons = []
    for a, b in combinations(names, 2):
        x = groups[a]
        y = groups[b]
        # remove NaNs
        x = x[np.isfinite(x)]
        y = y[np.isfinite(y)]
        if len(x) == 0 or len(y) == 0:
            stat, p = np.nan, np.nan
        else:
            # use two-sided
            stat, p = stats.mannwhitneyu(x, y, alternative="two-sided")
        comparisons.append({"g1": a, "g2": b, "stat": float(stat) if not np.isnan(stat) else np.nan, "p_uncorrected": float(p) if not np.isnan(p) else np.nan})

    # Bonferroni correction
    m = len(comparisons)
    for c in comparisons:
        if not np.isnan(c["p_uncorrected"]):
            c["p_bonf"] = min(1.0, c["p_uncorrected"] * m)
        else:
            c["p_bonf"] = np.nan

    return pd.DataFrame(comparisons)


# -----------------------
# LOAD DATA
# -----------------------
def load_data() -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load per-trial metrics (f1, mae) and metadata excel; join them by subject/timepoint.
    Returns merged DataFrame (one row per trial metric entry) with appended metadata fields.
    """
    if not PER_TRIAL_CSV.exists():
        raise FileNotFoundError(f"Per-trial CSV not found: {PER_TRIAL_CSV}")

    metrics_df = pd.read_csv(PER_TRIAL_CSV)
    # keep columns lowercase for consistency
    metrics_df.columns = [c.strip() for c in metrics_df.columns]

    # expected columns exist: filename, cohort, event_type, f1, mae
    required = {"filename", "cohort", "event_type", "f1", "mae"}
    if not required.issubset(set(metrics_df.columns)):
        raise ValueError(f"{PER_TRIAL_CSV} missing required cols {required - set(metrics_df.columns)}")

    # Load metadata excel
    if not METADATA_XLSX.exists():
        raise FileNotFoundError(f"Metadata Excel not found: {METADATA_XLSX}")
    meta = pd.read_excel(METADATA_XLSX)

    # Standardize: assume 'First_name' contains codes like INGC001 etc.
    if "First_name" not in meta.columns:
        raise ValueError("Metadata missing 'First_name' column")

    # Build joinable fields on metrics_df: subject_code, timepoint
    subj_codes = []
    tps = []
    for fname in metrics_df["filename"].astype(str).tolist():
        subj, tp = extract_subject_and_tp(fname)
        subj_codes.append(subj)
        tps.append(tp)
    metrics_df["subject_code"] = subj_codes
    metrics_df["timepoint"] = tps

    # Create merged rows by looking up the appropriate timepoint columns
    # For each row, pull age/hy/phen/nfog from meta row matching First_name == subject_code
    ages = []
    hys = []
    phens = []
    nfogs = []
    sexes = []
    cohorts_meta = []

    for idx, row in metrics_df.iterrows():
        subj = row["subject_code"]
        tp = row["timepoint"]
        if subj is None or tp is None or pd.isna(subj):
            ages.append(np.nan); hys.append(np.nan); phens.append(np.nan); nfogs.append(np.nan); sexes.append(np.nan); cohorts_meta.append(np.nan)
            continue
        # find metadata row for subject
        mr = meta[meta["First_name"].astype(str).str.upper() == str(subj).upper()]
        if mr.empty:
            ages.append(np.nan); hys.append(np.nan); phens.append(np.nan); nfogs.append(np.nan); sexes.append(np.nan); cohorts_meta.append(np.nan)
            continue
        # If multiple rows for same subject, take first (shouldn't happen frequently)
        mr0 = mr.iloc[0]
        # sex mapping (some columns in excel may be 'Sex_M0_F1' as you described)
        sex_field = "Sex_M0_F1" if "Sex_M0_F1" in meta.columns else None
        sex_val = mr0[sex_field] if sex_field is not None else (mr0.get("Sex", np.nan) if "Sex" in mr0 else np.nan)
        sexes.append(sex_val)

        # choose columns based on TIMEPOINT_MAP
        if tp in TIMEPOINT_MAP:
            mapping = TIMEPOINT_MAP[tp]
            age_col = mapping["age_col"]
            hy_col = mapping["hy_col"]
            phen_col = mapping["phen_col"]
            nfog_col = mapping["nfog_col"]
            # safe get (if column missing -> NaN)
            ages.append(mr0.get(age_col, np.nan))
            hys.append(mr0.get(hy_col, np.nan))
            phens.append(mr0.get(phen_col, np.nan))
            nfogs.append(mr0.get(nfog_col, np.nan))
            cohorts_meta.append(subj[3] if len(subj) >= 4 else np.nan)  # 'C' or 'P' inside INGC116
        else:
            ages.append(np.nan); hys.append(np.nan); phens.append(np.nan); nfogs.append(np.nan); cohorts_meta.append(np.nan)

    # append to metrics_df
    metrics_df["age"] = ages
    metrics_df["hy"] = hys
    metrics_df["phenotype"] = phens
    metrics_df["nfog"] = nfogs
    metrics_df["sex"] = sexes
    # cohort already exists, but ensure from subject if missing
    metrics_df["cohort_meta"] = cohorts_meta

    # create age_bin
    metrics_df["age_bin"] = metrics_df["age"].apply(lambda v: age_to_bin(v) if pd.notna(v) else "Unknown")

    return metrics_df, meta


# -----------------------
# ANALYSIS / PLOTTING
# -----------------------
def group_summary_stats(df: pd.DataFrame, group_col: str, metric_cols: List[str]) -> pd.DataFrame:
    """
    Return a DataFrame with group means/std/count for metric_cols.
    """
    agg = {}
    for m in metric_cols:
        agg[m + "_mean"] = (m, "mean")
        agg[m + "_std"] = (m, "std")
        agg[m + "_n"] = (m, "count")
    # perform grouped aggregation
    grouped = df.groupby(group_col).agg(**{k: pd.NamedAgg(column=v[0], aggfunc=v[1]) for k, v in agg.items()})
    grouped = grouped.reset_index()
    return grouped


def plot_group_boxplots(
    df: pd.DataFrame,
    group_col: str,
    event_type: str,
    out_png: Path,
    title_prefix: str,
    palette: Dict[str, str] | None = None,
):
    """
    Create a 2x1 figure: top = boxplot of F1 by group, bottom = boxplot of MAE by group.
    Colors assigned from palette (group->color).
    """
    groups = df[group_col].dropna().unique().tolist()
    groups = [g for g in groups if g != "Unknown"]
    groups = sorted(groups, key=lambda x: str(x))

    # Prepare data lists preserving order
    f1_data = [df.loc[df[group_col] == g, "f1"].dropna().astype(float).to_numpy() for g in groups]
    mae_data = [df.loc[df[group_col] == g, "mae"].dropna().astype(float).to_numpy() for g in groups]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(max(8, 1.2 * len(groups)), 8), sharex=True)
    fig.suptitle(f"{title_prefix} — {event_type} — per-trial (grouped by {group_col})", fontsize=14)

    # F1 boxplot
    bp1 = ax1.boxplot(f1_data, labels=groups, patch_artist=True, showfliers=False)
    for patch, g in zip(bp1["boxes"], groups):
        c = palette.get(g, "#777777") if palette else "#777777"
        patch.set_facecolor(c)
        patch.set_alpha(0.7)
    ax1.set_ylabel("F1")
    ax1.set_ylim([-0.05, 1.05])
    ax1.grid(axis="y", alpha=0.3)

    # MAE boxplot
    bp2 = ax2.boxplot(mae_data, labels=groups, patch_artist=True, showfliers=False)
    for patch, g in zip(bp2["boxes"], groups):
        c = palette.get(g, "#777777") if palette else "#777777"
        patch.set_facecolor(c)
        patch.set_alpha(0.7)
    ax2.set_ylabel("MAE (s)")
    ax2.grid(axis="y", alpha=0.3)

    plt.xticks(rotation=30, ha="right")
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    fig.savefig(out_png, dpi=300)
    plt.close(fig)


def run_stat_tests(df: pd.DataFrame, group_col: str, metric_col: str) -> Tuple[Dict[str, Any], pd.DataFrame | None]:
    """
    Run Kruskal-Wallis omnibus on groups in group_col for metric_col.
    If >2 groups, also do pairwise Mann-Whitney U with Bonferroni correction.
    Returns:
      - omnibus_result: dict with H, p, n_groups, group_counts
      - posthoc_df: pairwise comparisons df (or None if not applicable)
    """
    # prepare groups
    groups = {}
    for name, sub in df.groupby(group_col):
        arr = sub[metric_col].dropna().astype(float).to_numpy()
        if len(arr) > 0:
            groups[name] = arr

    group_names = list(groups.keys())
    counts = {k: len(groups[k]) for k in group_names}
    omnibus = {"H": np.nan, "p": np.nan, "n_groups": len(group_names), "counts": counts}

    if len(group_names) < 2:
        return omnibus, None

    # Kruskal-Wallis
    try:
        stats_args = [groups[k] for k in group_names]
        H, p = stats.kruskal(*stats_args)
        omnibus["H"] = float(H)
        omnibus["p"] = float(p)
    except Exception as e:
        omnibus["H"] = np.nan
        omnibus["p"] = np.nan

    posthoc_df = None
    if len(group_names) > 2:
        posthoc_df = pairwise_mwu_with_bonferroni(groups)
    elif len(group_names) == 2:
        # just compute the single MWU and return
        a, b = group_names
        x = groups[a]; y = groups[b]
        stat, pval = stats.mannwhitneyu(x, y, alternative="two-sided")
        posthoc_df = pd.DataFrame([{"g1": a, "g2": b, "stat": float(stat), "p_uncorrected": float(pval), "p_bonf": float(min(1.0, pval))}])

    return omnibus, posthoc_df


# -----------------------
# HIGH-LEVEL ANALYSIS
# -----------------------
def analyze_factor(
    metrics_df: pd.DataFrame,
    *,
    factor_col: str,
    factor_name: str,
    cohort_filter: str | None = None,
    event_type: str = "IC",
    palette: Dict[str, str] | None = None,
):
    """
    High-level wrapper: filter by cohort & event_type, compute group stats,
    draw plot, run tests, and save outputs.
    """
    df_sub = metrics_df.copy()
    if cohort_filter is not None:
        df_sub = df_sub[df_sub["cohort"] == cohort_filter].copy()

    df_sub = df_sub[df_sub["event_type"] == event_type].copy()
    if df_sub.empty:
        print(f"[SKIP] No rows for event_type={event_type} and cohort={cohort_filter}")
        return

    # group summary
    group_stats = group_summary_stats(df_sub, factor_col, ["f1", "mae"])
    out_prefix = f"{factor_name}_{event_type}" + (f"_{cohort_filter}" if cohort_filter else "")
    # save group stats
    csv_stats = PLOTS_OUTDIR / f"{out_prefix}_group_stats.csv"
    group_stats.to_csv(csv_stats, index=False)

    # plot
    png_path = PLOTS_OUTDIR / f"{out_prefix}_boxplots.png"
    plot_group_boxplots(df_sub, factor_col, event_type, png_path, title_prefix=factor_name, palette=palette)

    # tests (for both F1 and MAE)
    omnibus_f1, posthoc_f1 = run_stat_tests(df_sub, factor_col, "f1")
    omnibus_mae, posthoc_mae = run_stat_tests(df_sub, factor_col, "mae")

    # Build results dataframes
    omnibus_df = pd.DataFrame([{"metric": "f1", **omnibus_f1}, {"metric": "mae", **omnibus_mae}])
    omnibus_df.to_csv(PLOTS_OUTDIR / f"{out_prefix}_omnibus.csv", index=False)

    if posthoc_f1 is not None:
        posthoc_f1.to_csv(PLOTS_OUTDIR / f"{out_prefix}_posthoc_f1.csv", index=False)
    if posthoc_mae is not None:
        posthoc_mae.to_csv(PLOTS_OUTDIR / f"{out_prefix}_posthoc_mae.csv", index=False)

    print(f"[SAVED] {csv_stats}, {png_path}, omnibus & posthoc CSVs.")


# -----------------------
# MAIN
# -----------------------
def main():
    metrics_df, meta_df = load_data()

    # ensure essential columns exist types
    metrics_df["cohort"] = metrics_df["cohort"].astype(str)
    metrics_df["event_type"] = metrics_df["event_type"].astype(str).str.upper()
    metrics_df["sex"] = metrics_df["sex"].astype(object)

    # We'll run analyses for each event type (IC and FC)
    for event in ["IC", "FC"]:
        # 1) Age analysis: per-trial metrics averaged by age bins & cohort
        # Do both cohorts separately and together
        analyze_factor(metrics_df, factor_col="age_bin", factor_name="AgeBins", cohort_filter=None, event_type=event, palette=None)
        analyze_factor(metrics_df, factor_col="age_bin", factor_name="AgeBins", cohort_filter="C", event_type=event, palette=None)
        analyze_factor(metrics_df, factor_col="age_bin", factor_name="AgeBins", cohort_filter="P", event_type=event, palette=None)

        # 2) Sex analysis: male/female, separate cohorts
        analyze_factor(metrics_df, factor_col="sex", factor_name="Sex", cohort_filter=None, event_type=event, palette=None)
        analyze_factor(metrics_df, factor_col="sex", factor_name="Sex", cohort_filter="C", event_type=event, palette=None)
        analyze_factor(metrics_df, factor_col="sex", factor_name="Sex", cohort_filter="P", event_type=event, palette=None)

        # 3) Motor phenotype (PD only)
        analyze_factor(metrics_df, factor_col="phenotype", factor_name="MotorPhenotype", cohort_filter="P", event_type=event, palette=None)

        # 4) HY score (PD only)
        # ensure HY is integer-like
        metrics_df["hy_int"] = pd.to_numeric(metrics_df["hy"], errors="coerce").apply(lambda x: int(x) if pd.notna(x) else np.nan)
        analyze_factor(metrics_df, factor_col="hy_int", factor_name="HY_score", cohort_filter="P", event_type=event, palette=None)

        # 5) FOG presence (PD only) - treat numeric codes (0/1) or strings
        # normalize nfog to 'Yes'/'No'
        def _nfog_normalize(x):
            if pd.isna(x):
                return "Unknown"
            xs = str(x).strip()
            if xs in {"1", "Yes", "Y", "TRUE", "True", "true"}:
                return "FOG"
            if xs in {"0", "No", "N", "FALSE", "False", "false"}:
                return "NoFOG"
            return xs
        metrics_df["nfog_flag"] = metrics_df["nfog"].apply(_nfog_normalize)
        analyze_factor(metrics_df, factor_col="nfog_flag", factor_name="FOG", cohort_filter="P", event_type=event, palette=None)

    print("\nAll sub-analyses completed. Outputs saved under:")
    print(PLOTS_OUTDIR)


if __name__ == "__main__":
    main()